#!/usr/bin/env bash
# Configure nginx server with custom 404 page
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sed_string="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://w\
ww.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "s,server_name _;,$sed_string," /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed_string2="server_name _;\n\terror_page 404 /custom_404.html;\n\tlocation = /\
custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "s,server_name _;,$sed_string2," /etc/nginx/sites-enabled/default
service nginx restart
