#!/usr/bin/env bash

# Create the PID file
echo $$ > /var/run/myscript.pid

# Define signal handlers
function sigterm_handler {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}

function sigint_handler {
    echo "Y U no love me?!"
}

function sigquit_handler {
    rm /var/run/myscript.pid
    exit 0
}

# Register signal handlers
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
