#!/usr/bin/env bash
# This script is displaying Best School 9 times and 1 hi

counter=1

while [ $counter -le 10 ]
do 
if [ $counter -eq 9 ]; then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
(( counter++ ))
done
